---  
- include_tasks: encrypt_credentials.yml
  with_items: 
        - { name: '{{ item }}_access_key_id', value: '{{ item }}_access_key_id' }
        - { name: '{{ item }}_secret_access_key', value: '{{ item }}_secret_access_key' }

- set_fact: 
    access_key_enc: "{{ lookup('vars', item + '_access_key_id_enc' ) }}"
    secret_key_enc: "{{ lookup('vars', item + '_secret_access_key_enc' ) }}"

- name: Template AWS credentials
  template: 
    src: aws_credentials/aws_credentials.yml.j2
    dest: inventories/group_vars/all/{{ item }}_aws_credentials.yml